version: "3.3" # version of docker compose
services: # define services or containers that run the application 
  api: #api service
    container_name: dev1
    build: ./dev1/ 
    ports:
      - "5000:5000"
    volumes:
      - type: volume
        source: dev1-vol
        target: /app # location within the container that we want to populate in the volume
  nodered: #nodered service
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - type: volume
        source: nodered-vol
        target: /data
volumes: # defines volumes block
  dev1-vol: {} # name of volume
  nodered-vol: {}